// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/locald/api/rootmanager/root_manager_api.proto

package rootmanager

import (
	api "github.com/signadot/cli/internal/locald/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Localnet      *api.LocalNetStatus    `protobuf:"bytes,1,opt,name=localnet,proto3" json:"localnet,omitempty"`
	Hosts         *api.HostsStatus       `protobuf:"bytes,2,opt,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetLocalnet() *api.LocalNetStatus {
	if x != nil {
		return x.Localnet
	}
	return nil
}

func (x *StatusResponse) GetHosts() *api.HostsStatus {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescGZIP(), []int{2}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescGZIP(), []int{3}
}

var File_internal_locald_api_rootmanager_root_manager_api_proto protoreflect.FileDescriptor

const file_internal_locald_api_rootmanager_root_manager_api_proto_rawDesc = "" +
	"\n" +
	"6internal/locald/api/rootmanager/root_manager_api.proto\x12\vrootmanager\x1a internal/locald/api/common.proto\"\x0f\n" +
	"\rStatusRequest\"u\n" +
	"\x0eStatusResponse\x125\n" +
	"\blocalnet\x18\x01 \x01(\v2\x19.apicommon.LocalNetStatusR\blocalnet\x12,\n" +
	"\x05hosts\x18\x02 \x01(\v2\x16.apicommon.HostsStatusR\x05hosts\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\xa0\x01\n" +
	"\x0eRootManagerAPI\x12C\n" +
	"\x06Status\x12\x1a.rootmanager.StatusRequest\x1a\x1b.rootmanager.StatusResponse\"\x00\x12I\n" +
	"\bShutdown\x12\x1c.rootmanager.ShutdownRequest\x1a\x1d.rootmanager.ShutdownResponse\"\x00B9Z7github.com/signadot/cli/internal/locald/api/rootmanagerb\x06proto3"

var (
	file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescOnce sync.Once
	file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescData []byte
)

func file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescGZIP() []byte {
	file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescOnce.Do(func() {
		file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_locald_api_rootmanager_root_manager_api_proto_rawDesc), len(file_internal_locald_api_rootmanager_root_manager_api_proto_rawDesc)))
	})
	return file_internal_locald_api_rootmanager_root_manager_api_proto_rawDescData
}

var file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_locald_api_rootmanager_root_manager_api_proto_goTypes = []any{
	(*StatusRequest)(nil),      // 0: rootmanager.StatusRequest
	(*StatusResponse)(nil),     // 1: rootmanager.StatusResponse
	(*ShutdownRequest)(nil),    // 2: rootmanager.ShutdownRequest
	(*ShutdownResponse)(nil),   // 3: rootmanager.ShutdownResponse
	(*api.LocalNetStatus)(nil), // 4: apicommon.LocalNetStatus
	(*api.HostsStatus)(nil),    // 5: apicommon.HostsStatus
}
var file_internal_locald_api_rootmanager_root_manager_api_proto_depIdxs = []int32{
	4, // 0: rootmanager.StatusResponse.localnet:type_name -> apicommon.LocalNetStatus
	5, // 1: rootmanager.StatusResponse.hosts:type_name -> apicommon.HostsStatus
	0, // 2: rootmanager.RootManagerAPI.Status:input_type -> rootmanager.StatusRequest
	2, // 3: rootmanager.RootManagerAPI.Shutdown:input_type -> rootmanager.ShutdownRequest
	1, // 4: rootmanager.RootManagerAPI.Status:output_type -> rootmanager.StatusResponse
	3, // 5: rootmanager.RootManagerAPI.Shutdown:output_type -> rootmanager.ShutdownResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_locald_api_rootmanager_root_manager_api_proto_init() }
func file_internal_locald_api_rootmanager_root_manager_api_proto_init() {
	if File_internal_locald_api_rootmanager_root_manager_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_locald_api_rootmanager_root_manager_api_proto_rawDesc), len(file_internal_locald_api_rootmanager_root_manager_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_locald_api_rootmanager_root_manager_api_proto_goTypes,
		DependencyIndexes: file_internal_locald_api_rootmanager_root_manager_api_proto_depIdxs,
		MessageInfos:      file_internal_locald_api_rootmanager_root_manager_api_proto_msgTypes,
	}.Build()
	File_internal_locald_api_rootmanager_root_manager_api_proto = out.File
	file_internal_locald_api_rootmanager_root_manager_api_proto_goTypes = nil
	file_internal_locald_api_rootmanager_root_manager_api_proto_depIdxs = nil
}
