// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: internal/locald/api/rootmanager/root_manager_api.proto

package rootmanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RootManagerAPIClient is the client API for RootManagerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RootManagerAPIClient interface {
	// This method returns the status of the root controller
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// This method requests the root controller to shutdown
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type rootManagerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewRootManagerAPIClient(cc grpc.ClientConnInterface) RootManagerAPIClient {
	return &rootManagerAPIClient{cc}
}

func (c *rootManagerAPIClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/rootmanager.RootManagerAPI/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootManagerAPIClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/rootmanager.RootManagerAPI/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RootManagerAPIServer is the server API for RootManagerAPI service.
// All implementations must embed UnimplementedRootManagerAPIServer
// for forward compatibility
type RootManagerAPIServer interface {
	// This method returns the status of the root controller
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// This method requests the root controller to shutdown
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedRootManagerAPIServer()
}

// UnimplementedRootManagerAPIServer must be embedded to have forward compatible implementations.
type UnimplementedRootManagerAPIServer struct {
}

func (UnimplementedRootManagerAPIServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedRootManagerAPIServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedRootManagerAPIServer) mustEmbedUnimplementedRootManagerAPIServer() {}

// UnsafeRootManagerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RootManagerAPIServer will
// result in compilation errors.
type UnsafeRootManagerAPIServer interface {
	mustEmbedUnimplementedRootManagerAPIServer()
}

func RegisterRootManagerAPIServer(s grpc.ServiceRegistrar, srv RootManagerAPIServer) {
	s.RegisterService(&RootManagerAPI_ServiceDesc, srv)
}

func _RootManagerAPI_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootManagerAPIServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rootmanager.RootManagerAPI/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootManagerAPIServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootManagerAPI_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootManagerAPIServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rootmanager.RootManagerAPI/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootManagerAPIServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RootManagerAPI_ServiceDesc is the grpc.ServiceDesc for RootManagerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RootManagerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rootmanager.RootManagerAPI",
	HandlerType: (*RootManagerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _RootManagerAPI_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _RootManagerAPI_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/locald/api/rootmanager/root_manager_api.proto",
}
