// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/locald/api/common.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service health
type ServiceHealth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Healthy         bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ErrorCount      uint32                 `protobuf:"varint,2,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	LastErrorReason string                 `protobuf:"bytes,3,opt,name=last_error_reason,json=lastErrorReason,proto3" json:"last_error_reason,omitempty"`
	LastErrorTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_error_time,json=lastErrorTime,proto3" json:"last_error_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceHealth) Reset() {
	*x = ServiceHealth{}
	mi := &file_internal_locald_api_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealth) ProtoMessage() {}

func (x *ServiceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealth.ProtoReflect.Descriptor instead.
func (*ServiceHealth) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ServiceHealth) GetErrorCount() uint32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ServiceHealth) GetLastErrorReason() string {
	if x != nil {
		return x.LastErrorReason
	}
	return ""
}

func (x *ServiceHealth) GetLastErrorTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastErrorTime
	}
	return nil
}

// LocalNet status (produced by root controller)
type LocalNetStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *ServiceHealth         `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	Cidrs         []string               `protobuf:"bytes,2,rep,name=cidrs,proto3" json:"cidrs,omitempty"`
	ExcludedCidrs []string               `protobuf:"bytes,3,rep,name=excluded_cidrs,json=excludedCidrs,proto3" json:"excluded_cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalNetStatus) Reset() {
	*x = LocalNetStatus{}
	mi := &file_internal_locald_api_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalNetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalNetStatus) ProtoMessage() {}

func (x *LocalNetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalNetStatus.ProtoReflect.Descriptor instead.
func (*LocalNetStatus) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *LocalNetStatus) GetHealth() *ServiceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *LocalNetStatus) GetCidrs() []string {
	if x != nil {
		return x.Cidrs
	}
	return nil
}

func (x *LocalNetStatus) GetExcludedCidrs() []string {
	if x != nil {
		return x.ExcludedCidrs
	}
	return nil
}

// Hosts status (produced by root controller)
type HostsStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Health         *ServiceHealth         `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	NumHosts       uint32                 `protobuf:"varint,2,opt,name=num_hosts,json=numHosts,proto3" json:"num_hosts,omitempty"`
	NumUpdates     uint32                 `protobuf:"varint,3,opt,name=num_updates,json=numUpdates,proto3" json:"num_updates,omitempty"`
	LastUpdateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostsStatus) Reset() {
	*x = HostsStatus{}
	mi := &file_internal_locald_api_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostsStatus) ProtoMessage() {}

func (x *HostsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostsStatus.ProtoReflect.Descriptor instead.
func (*HostsStatus) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{2}
}

func (x *HostsStatus) GetHealth() *ServiceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *HostsStatus) GetNumHosts() uint32 {
	if x != nil {
		return x.NumHosts
	}
	return 0
}

func (x *HostsStatus) GetNumUpdates() uint32 {
	if x != nil {
		return x.NumUpdates
	}
	return 0
}

func (x *HostsStatus) GetLastUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdateTime
	}
	return nil
}

// PortForward status (produced by local controller)
type PortForwardStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *ServiceHealth         `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	LocalAddress  string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardStatus) Reset() {
	*x = PortForwardStatus{}
	mi := &file_internal_locald_api_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardStatus) ProtoMessage() {}

func (x *PortForwardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardStatus.ProtoReflect.Descriptor instead.
func (*PortForwardStatus) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{3}
}

func (x *PortForwardStatus) GetHealth() *ServiceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *PortForwardStatus) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

// ControlPlaneProxy status (produced by local controller)
type ControlPlaneProxyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *ServiceHealth         `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	LocalAddress  string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlaneProxyStatus) Reset() {
	*x = ControlPlaneProxyStatus{}
	mi := &file_internal_locald_api_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneProxyStatus) ProtoMessage() {}

func (x *ControlPlaneProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneProxyStatus.ProtoReflect.Descriptor instead.
func (*ControlPlaneProxyStatus) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{4}
}

func (x *ControlPlaneProxyStatus) GetHealth() *ServiceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *ControlPlaneProxyStatus) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

// Sandboxes watcher status (produced by local controller)
type WatcherStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *ServiceHealth         `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatcherStatus) Reset() {
	*x = WatcherStatus{}
	mi := &file_internal_locald_api_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatcherStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherStatus) ProtoMessage() {}

func (x *WatcherStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherStatus.ProtoReflect.Descriptor instead.
func (*WatcherStatus) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{5}
}

func (x *WatcherStatus) GetHealth() *ServiceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

// Sandbox status (produced by local controller)
type SandboxStatus struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	Name           string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RoutingKey     string                         `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	LocalWorkloads []*SandboxStatus_LocalWorkload `protobuf:"bytes,3,rep,name=local_workloads,json=localWorkloads,proto3" json:"local_workloads,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxStatus) Reset() {
	*x = SandboxStatus{}
	mi := &file_internal_locald_api_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus) ProtoMessage() {}

func (x *SandboxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus.ProtoReflect.Descriptor instead.
func (*SandboxStatus) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxStatus) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *SandboxStatus) GetLocalWorkloads() []*SandboxStatus_LocalWorkload {
	if x != nil {
		return x.LocalWorkloads
	}
	return nil
}

type OperatorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GitCommit     string                 `protobuf:"bytes,2,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	BuildDate     string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorInfo) Reset() {
	*x = OperatorInfo{}
	mi := &file_internal_locald_api_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorInfo) ProtoMessage() {}

func (x *OperatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorInfo.ProtoReflect.Descriptor instead.
func (*OperatorInfo) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{7}
}

func (x *OperatorInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OperatorInfo) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *OperatorInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

// Devbox session status (produced by local controller)
type DevboxSessionStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the devbox session is active and healthy
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Whether the session was released by another process
	SessionReleased bool `protobuf:"varint,2,opt,name=session_released,json=sessionReleased,proto3" json:"session_released,omitempty"`
	// Devbox ID
	DevboxId string `protobuf:"bytes,3,opt,name=devbox_id,json=devboxId,proto3" json:"devbox_id,omitempty"`
	// Session ID
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Last error reason if unhealthy
	LastErrorReason string `protobuf:"bytes,5,opt,name=last_error_reason,json=lastErrorReason,proto3" json:"last_error_reason,omitempty"`
	// Last error time if unhealthy
	LastErrorTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_error_time,json=lastErrorTime,proto3" json:"last_error_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevboxSessionStatus) Reset() {
	*x = DevboxSessionStatus{}
	mi := &file_internal_locald_api_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevboxSessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevboxSessionStatus) ProtoMessage() {}

func (x *DevboxSessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevboxSessionStatus.ProtoReflect.Descriptor instead.
func (*DevboxSessionStatus) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{8}
}

func (x *DevboxSessionStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *DevboxSessionStatus) GetSessionReleased() bool {
	if x != nil {
		return x.SessionReleased
	}
	return false
}

func (x *DevboxSessionStatus) GetDevboxId() string {
	if x != nil {
		return x.DevboxId
	}
	return ""
}

func (x *DevboxSessionStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DevboxSessionStatus) GetLastErrorReason() string {
	if x != nil {
		return x.LastErrorReason
	}
	return ""
}

func (x *DevboxSessionStatus) GetLastErrorTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastErrorTime
	}
	return nil
}

type SandboxStatus_Baseline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStatus_Baseline) Reset() {
	*x = SandboxStatus_Baseline{}
	mi := &file_internal_locald_api_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus_Baseline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus_Baseline) ProtoMessage() {}

func (x *SandboxStatus_Baseline) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus_Baseline.ProtoReflect.Descriptor instead.
func (*SandboxStatus_Baseline) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SandboxStatus_Baseline) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SandboxStatus_Baseline) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SandboxStatus_Baseline) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SandboxStatus_Baseline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SandboxStatus_BaselineToLocal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaselinePort  int32                  `protobuf:"varint,1,opt,name=baseline_port,json=baselinePort,proto3" json:"baseline_port,omitempty"`
	LocalAddress  string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStatus_BaselineToLocal) Reset() {
	*x = SandboxStatus_BaselineToLocal{}
	mi := &file_internal_locald_api_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus_BaselineToLocal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus_BaselineToLocal) ProtoMessage() {}

func (x *SandboxStatus_BaselineToLocal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus_BaselineToLocal.ProtoReflect.Descriptor instead.
func (*SandboxStatus_BaselineToLocal) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{6, 1}
}

func (x *SandboxStatus_BaselineToLocal) GetBaselinePort() int32 {
	if x != nil {
		return x.BaselinePort
	}
	return 0
}

func (x *SandboxStatus_BaselineToLocal) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

type SandboxStatus_LocalWorkload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workload name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// "fork target"
	Baseline *SandboxStatus_Baseline `protobuf:"bytes,2,opt,name=baseline,proto3" json:"baseline,omitempty"`
	// associative map from baseline ports to local address
	// destinations in the tunnel
	WorkloadPortMapping []*SandboxStatus_BaselineToLocal `protobuf:"bytes,3,rep,name=workloadPortMapping,proto3" json:"workloadPortMapping,omitempty"`
	// tunnel health
	TunnelHealth  *ServiceHealth `protobuf:"bytes,4,opt,name=tunnel_health,json=tunnelHealth,proto3" json:"tunnel_health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStatus_LocalWorkload) Reset() {
	*x = SandboxStatus_LocalWorkload{}
	mi := &file_internal_locald_api_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus_LocalWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus_LocalWorkload) ProtoMessage() {}

func (x *SandboxStatus_LocalWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_locald_api_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus_LocalWorkload.ProtoReflect.Descriptor instead.
func (*SandboxStatus_LocalWorkload) Descriptor() ([]byte, []int) {
	return file_internal_locald_api_common_proto_rawDescGZIP(), []int{6, 2}
}

func (x *SandboxStatus_LocalWorkload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxStatus_LocalWorkload) GetBaseline() *SandboxStatus_Baseline {
	if x != nil {
		return x.Baseline
	}
	return nil
}

func (x *SandboxStatus_LocalWorkload) GetWorkloadPortMapping() []*SandboxStatus_BaselineToLocal {
	if x != nil {
		return x.WorkloadPortMapping
	}
	return nil
}

func (x *SandboxStatus_LocalWorkload) GetTunnelHealth() *ServiceHealth {
	if x != nil {
		return x.TunnelHealth
	}
	return nil
}

var File_internal_locald_api_common_proto protoreflect.FileDescriptor

const file_internal_locald_api_common_proto_rawDesc = "" +
	"\n" +
	" internal/locald/api/common.proto\x12\tapicommon\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\rServiceHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1f\n" +
	"\verror_count\x18\x02 \x01(\rR\n" +
	"errorCount\x12*\n" +
	"\x11last_error_reason\x18\x03 \x01(\tR\x0flastErrorReason\x12B\n" +
	"\x0flast_error_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastErrorTime\"\x7f\n" +
	"\x0eLocalNetStatus\x120\n" +
	"\x06health\x18\x01 \x01(\v2\x18.apicommon.ServiceHealthR\x06health\x12\x14\n" +
	"\x05cidrs\x18\x02 \x03(\tR\x05cidrs\x12%\n" +
	"\x0eexcluded_cidrs\x18\x03 \x03(\tR\rexcludedCidrs\"\xc3\x01\n" +
	"\vHostsStatus\x120\n" +
	"\x06health\x18\x01 \x01(\v2\x18.apicommon.ServiceHealthR\x06health\x12\x1b\n" +
	"\tnum_hosts\x18\x02 \x01(\rR\bnumHosts\x12\x1f\n" +
	"\vnum_updates\x18\x03 \x01(\rR\n" +
	"numUpdates\x12D\n" +
	"\x10last_update_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastUpdateTime\"j\n" +
	"\x11PortForwardStatus\x120\n" +
	"\x06health\x18\x01 \x01(\v2\x18.apicommon.ServiceHealthR\x06health\x12#\n" +
	"\rlocal_address\x18\x02 \x01(\tR\flocalAddress\"p\n" +
	"\x17ControlPlaneProxyStatus\x120\n" +
	"\x06health\x18\x01 \x01(\v2\x18.apicommon.ServiceHealthR\x06health\x12#\n" +
	"\rlocal_address\x18\x02 \x01(\tR\flocalAddress\"A\n" +
	"\rWatcherStatus\x120\n" +
	"\x06health\x18\x01 \x01(\v2\x18.apicommon.ServiceHealthR\x06health\"\xe4\x04\n" +
	"\rSandboxStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12O\n" +
	"\x0flocal_workloads\x18\x03 \x03(\v2&.apicommon.SandboxStatus.LocalWorkloadR\x0elocalWorkloads\x1ap\n" +
	"\bBaseline\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x1a[\n" +
	"\x0fBaselineToLocal\x12#\n" +
	"\rbaseline_port\x18\x01 \x01(\x05R\fbaselinePort\x12#\n" +
	"\rlocal_address\x18\x02 \x01(\tR\flocalAddress\x1a\xfd\x01\n" +
	"\rLocalWorkload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\bbaseline\x18\x02 \x01(\v2!.apicommon.SandboxStatus.BaselineR\bbaseline\x12Z\n" +
	"\x13workloadPortMapping\x18\x03 \x03(\v2(.apicommon.SandboxStatus.BaselineToLocalR\x13workloadPortMapping\x12=\n" +
	"\rtunnel_health\x18\x04 \x01(\v2\x18.apicommon.ServiceHealthR\ftunnelHealth\"f\n" +
	"\fOperatorInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x02 \x01(\tR\tgitCommit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\"\x86\x02\n" +
	"\x13DevboxSessionStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12)\n" +
	"\x10session_released\x18\x02 \x01(\bR\x0fsessionReleased\x12\x1b\n" +
	"\tdevbox_id\x18\x03 \x01(\tR\bdevboxId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12*\n" +
	"\x11last_error_reason\x18\x05 \x01(\tR\x0flastErrorReason\x12B\n" +
	"\x0flast_error_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastErrorTimeB-Z+github.com/signadot/cli/internal/locald/apib\x06proto3"

var (
	file_internal_locald_api_common_proto_rawDescOnce sync.Once
	file_internal_locald_api_common_proto_rawDescData []byte
)

func file_internal_locald_api_common_proto_rawDescGZIP() []byte {
	file_internal_locald_api_common_proto_rawDescOnce.Do(func() {
		file_internal_locald_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_locald_api_common_proto_rawDesc), len(file_internal_locald_api_common_proto_rawDesc)))
	})
	return file_internal_locald_api_common_proto_rawDescData
}

var file_internal_locald_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_locald_api_common_proto_goTypes = []any{
	(*ServiceHealth)(nil),                 // 0: apicommon.ServiceHealth
	(*LocalNetStatus)(nil),                // 1: apicommon.LocalNetStatus
	(*HostsStatus)(nil),                   // 2: apicommon.HostsStatus
	(*PortForwardStatus)(nil),             // 3: apicommon.PortForwardStatus
	(*ControlPlaneProxyStatus)(nil),       // 4: apicommon.ControlPlaneProxyStatus
	(*WatcherStatus)(nil),                 // 5: apicommon.WatcherStatus
	(*SandboxStatus)(nil),                 // 6: apicommon.SandboxStatus
	(*OperatorInfo)(nil),                  // 7: apicommon.OperatorInfo
	(*DevboxSessionStatus)(nil),           // 8: apicommon.DevboxSessionStatus
	(*SandboxStatus_Baseline)(nil),        // 9: apicommon.SandboxStatus.Baseline
	(*SandboxStatus_BaselineToLocal)(nil), // 10: apicommon.SandboxStatus.BaselineToLocal
	(*SandboxStatus_LocalWorkload)(nil),   // 11: apicommon.SandboxStatus.LocalWorkload
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
}
var file_internal_locald_api_common_proto_depIdxs = []int32{
	12, // 0: apicommon.ServiceHealth.last_error_time:type_name -> google.protobuf.Timestamp
	0,  // 1: apicommon.LocalNetStatus.health:type_name -> apicommon.ServiceHealth
	0,  // 2: apicommon.HostsStatus.health:type_name -> apicommon.ServiceHealth
	12, // 3: apicommon.HostsStatus.last_update_time:type_name -> google.protobuf.Timestamp
	0,  // 4: apicommon.PortForwardStatus.health:type_name -> apicommon.ServiceHealth
	0,  // 5: apicommon.ControlPlaneProxyStatus.health:type_name -> apicommon.ServiceHealth
	0,  // 6: apicommon.WatcherStatus.health:type_name -> apicommon.ServiceHealth
	11, // 7: apicommon.SandboxStatus.local_workloads:type_name -> apicommon.SandboxStatus.LocalWorkload
	12, // 8: apicommon.DevboxSessionStatus.last_error_time:type_name -> google.protobuf.Timestamp
	9,  // 9: apicommon.SandboxStatus.LocalWorkload.baseline:type_name -> apicommon.SandboxStatus.Baseline
	10, // 10: apicommon.SandboxStatus.LocalWorkload.workloadPortMapping:type_name -> apicommon.SandboxStatus.BaselineToLocal
	0,  // 11: apicommon.SandboxStatus.LocalWorkload.tunnel_health:type_name -> apicommon.ServiceHealth
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_locald_api_common_proto_init() }
func file_internal_locald_api_common_proto_init() {
	if File_internal_locald_api_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_locald_api_common_proto_rawDesc), len(file_internal_locald_api_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_locald_api_common_proto_goTypes,
		DependencyIndexes: file_internal_locald_api_common_proto_depIdxs,
		MessageInfos:      file_internal_locald_api_common_proto_msgTypes,
	}.Build()
	File_internal_locald_api_common_proto = out.File
	file_internal_locald_api_common_proto_goTypes = nil
	file_internal_locald_api_common_proto_depIdxs = nil
}
