// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: internal/locald/api/sandboxmanager/sandbox_manager_api.proto

package sandboxmanager

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SandboxManagerAPIClient is the client API for SandboxManagerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxManagerAPIClient interface {
	// This method returns the status of the local controller
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// This method requests the root controller to shutdown
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// This method is used to register sandboxes in the local controller. It is
	// mainly used in the context of old operators (the ones that don't support
	// WatchLocalSandboxes in tunnel-api)
	RegisterSandbox(ctx context.Context, in *RegisterSandboxRequest, opts ...grpc.CallOption) (*RegisterSandboxResponse, error)
}

type sandboxManagerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxManagerAPIClient(cc grpc.ClientConnInterface) SandboxManagerAPIClient {
	return &sandboxManagerAPIClient{cc}
}

func (c *sandboxManagerAPIClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/sandboxmanager.SandboxManagerAPI/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxManagerAPIClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/sandboxmanager.SandboxManagerAPI/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxManagerAPIClient) RegisterSandbox(ctx context.Context, in *RegisterSandboxRequest, opts ...grpc.CallOption) (*RegisterSandboxResponse, error) {
	out := new(RegisterSandboxResponse)
	err := c.cc.Invoke(ctx, "/sandboxmanager.SandboxManagerAPI/RegisterSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxManagerAPIServer is the server API for SandboxManagerAPI service.
// All implementations must embed UnimplementedSandboxManagerAPIServer
// for forward compatibility
type SandboxManagerAPIServer interface {
	// This method returns the status of the local controller
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// This method requests the root controller to shutdown
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// This method is used to register sandboxes in the local controller. It is
	// mainly used in the context of old operators (the ones that don't support
	// WatchLocalSandboxes in tunnel-api)
	RegisterSandbox(context.Context, *RegisterSandboxRequest) (*RegisterSandboxResponse, error)
	mustEmbedUnimplementedSandboxManagerAPIServer()
}

// UnimplementedSandboxManagerAPIServer must be embedded to have forward compatible implementations.
type UnimplementedSandboxManagerAPIServer struct {
}

func (UnimplementedSandboxManagerAPIServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSandboxManagerAPIServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedSandboxManagerAPIServer) RegisterSandbox(context.Context, *RegisterSandboxRequest) (*RegisterSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSandbox not implemented")
}
func (UnimplementedSandboxManagerAPIServer) mustEmbedUnimplementedSandboxManagerAPIServer() {}

// UnsafeSandboxManagerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxManagerAPIServer will
// result in compilation errors.
type UnsafeSandboxManagerAPIServer interface {
	mustEmbedUnimplementedSandboxManagerAPIServer()
}

func RegisterSandboxManagerAPIServer(s grpc.ServiceRegistrar, srv SandboxManagerAPIServer) {
	s.RegisterService(&SandboxManagerAPI_ServiceDesc, srv)
}

func _SandboxManagerAPI_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxManagerAPIServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandboxmanager.SandboxManagerAPI/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxManagerAPIServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxManagerAPI_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxManagerAPIServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandboxmanager.SandboxManagerAPI/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxManagerAPIServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxManagerAPI_RegisterSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxManagerAPIServer).RegisterSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandboxmanager.SandboxManagerAPI/RegisterSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxManagerAPIServer).RegisterSandbox(ctx, req.(*RegisterSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxManagerAPI_ServiceDesc is the grpc.ServiceDesc for SandboxManagerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxManagerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandboxmanager.SandboxManagerAPI",
	HandlerType: (*SandboxManagerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _SandboxManagerAPI_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _SandboxManagerAPI_Shutdown_Handler,
		},
		{
			MethodName: "RegisterSandbox",
			Handler:    _SandboxManagerAPI_RegisterSandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/locald/api/sandboxmanager/sandbox_manager_api.proto",
}
