// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: internal/api/localctrlapi/local_controller_api.proto

package localctrlapi

import (
	api "github.com/signadot/cli/internal/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplySandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sandbox name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// sandbox spec (instance of github.com/signadot/go-sdk/models.SandboxSpec)
	SandboxSpec *structpb.Struct `protobuf:"bytes,2,opt,name=sandbox_spec,json=sandboxSpec,proto3" json:"sandbox_spec,omitempty"`
}

func (x *ApplySandboxRequest) Reset() {
	*x = ApplySandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplySandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySandboxRequest) ProtoMessage() {}

func (x *ApplySandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySandboxRequest.ProtoReflect.Descriptor instead.
func (*ApplySandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_localctrlapi_local_controller_api_proto_rawDescGZIP(), []int{0}
}

func (x *ApplySandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplySandboxRequest) GetSandboxSpec() *structpb.Struct {
	if x != nil {
		return x.SandboxSpec
	}
	return nil
}

type ApplySandboxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sandbox (instance of github.com/signadot/go-sdk/models.Sandbox)
	Sandbox *structpb.Struct `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
}

func (x *ApplySandboxResponse) Reset() {
	*x = ApplySandboxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplySandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySandboxResponse) ProtoMessage() {}

func (x *ApplySandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySandboxResponse.ProtoReflect.Descriptor instead.
func (*ApplySandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_localctrlapi_local_controller_api_proto_rawDescGZIP(), []int{1}
}

func (x *ApplySandboxResponse) GetSandbox() *structpb.Struct {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_localctrlapi_local_controller_api_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Localnet   *api.LocalNetStatus    `protobuf:"bytes,1,opt,name=localnet,proto3" json:"localnet,omitempty"`
	Hosts      *api.HostsStatus       `protobuf:"bytes,2,opt,name=hosts,proto3" json:"hosts,omitempty"`
	Portfoward *api.PortForwardStatus `protobuf:"bytes,3,opt,name=portfoward,proto3" json:"portfoward,omitempty"`
	Sandboxes  []*api.SandboxStatus   `protobuf:"bytes,4,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_localctrlapi_local_controller_api_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetLocalnet() *api.LocalNetStatus {
	if x != nil {
		return x.Localnet
	}
	return nil
}

func (x *StatusResponse) GetHosts() *api.HostsStatus {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *StatusResponse) GetPortfoward() *api.PortForwardStatus {
	if x != nil {
		return x.Portfoward
	}
	return nil
}

func (x *StatusResponse) GetSandboxes() []*api.SandboxStatus {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

var File_internal_api_localctrlapi_local_controller_api_proto protoreflect.FileDescriptor

var file_internal_api_localctrlapi_local_controller_api_proto_rawDesc = []byte{
	0x0a, 0x34, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x63, 0x74, 0x72, 0x6c, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x74, 0x72,
	0x6c, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a,
	0x13, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x53, 0x70, 0x65, 0x63, 0x22, 0x49, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x53, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x22,
	0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xeb, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x6e, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x6e, 0x65, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x68, 0x6f,
	0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x0a, 0x70, 0x6f, 0x72, 0x74,
	0x66, 0x6f, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61,
	0x70, 0x69, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x70, 0x6f, 0x72, 0x74,
	0x66, 0x6f, 0x77, 0x61, 0x72, 0x64, 0x12, 0x36, 0x0a, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x32, 0xb4,
	0x01, 0x0a, 0x12, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x41, 0x50, 0x49, 0x12, 0x57, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x53, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x12, 0x21, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x74, 0x72,
	0x6c, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x63, 0x74, 0x72, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x53, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x63, 0x74, 0x72, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x74, 0x72,
	0x6c, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f, 0x74, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x63, 0x74, 0x72, 0x6c, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_api_localctrlapi_local_controller_api_proto_rawDescOnce sync.Once
	file_internal_api_localctrlapi_local_controller_api_proto_rawDescData = file_internal_api_localctrlapi_local_controller_api_proto_rawDesc
)

func file_internal_api_localctrlapi_local_controller_api_proto_rawDescGZIP() []byte {
	file_internal_api_localctrlapi_local_controller_api_proto_rawDescOnce.Do(func() {
		file_internal_api_localctrlapi_local_controller_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_localctrlapi_local_controller_api_proto_rawDescData)
	})
	return file_internal_api_localctrlapi_local_controller_api_proto_rawDescData
}

var file_internal_api_localctrlapi_local_controller_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_api_localctrlapi_local_controller_api_proto_goTypes = []interface{}{
	(*ApplySandboxRequest)(nil),   // 0: localctrlapi.ApplySandboxRequest
	(*ApplySandboxResponse)(nil),  // 1: localctrlapi.ApplySandboxResponse
	(*StatusRequest)(nil),         // 2: localctrlapi.StatusRequest
	(*StatusResponse)(nil),        // 3: localctrlapi.StatusResponse
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
	(*api.LocalNetStatus)(nil),    // 5: apicommon.LocalNetStatus
	(*api.HostsStatus)(nil),       // 6: apicommon.HostsStatus
	(*api.PortForwardStatus)(nil), // 7: apicommon.PortForwardStatus
	(*api.SandboxStatus)(nil),     // 8: apicommon.SandboxStatus
}
var file_internal_api_localctrlapi_local_controller_api_proto_depIdxs = []int32{
	4, // 0: localctrlapi.ApplySandboxRequest.sandbox_spec:type_name -> google.protobuf.Struct
	4, // 1: localctrlapi.ApplySandboxResponse.sandbox:type_name -> google.protobuf.Struct
	5, // 2: localctrlapi.StatusResponse.localnet:type_name -> apicommon.LocalNetStatus
	6, // 3: localctrlapi.StatusResponse.hosts:type_name -> apicommon.HostsStatus
	7, // 4: localctrlapi.StatusResponse.portfoward:type_name -> apicommon.PortForwardStatus
	8, // 5: localctrlapi.StatusResponse.sandboxes:type_name -> apicommon.SandboxStatus
	0, // 6: localctrlapi.LocalControllerAPI.ApplySandbox:input_type -> localctrlapi.ApplySandboxRequest
	2, // 7: localctrlapi.LocalControllerAPI.Status:input_type -> localctrlapi.StatusRequest
	1, // 8: localctrlapi.LocalControllerAPI.ApplySandbox:output_type -> localctrlapi.ApplySandboxResponse
	3, // 9: localctrlapi.LocalControllerAPI.Status:output_type -> localctrlapi.StatusResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_api_localctrlapi_local_controller_api_proto_init() }
func file_internal_api_localctrlapi_local_controller_api_proto_init() {
	if File_internal_api_localctrlapi_local_controller_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplySandboxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplySandboxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_localctrlapi_local_controller_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_localctrlapi_local_controller_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_localctrlapi_local_controller_api_proto_goTypes,
		DependencyIndexes: file_internal_api_localctrlapi_local_controller_api_proto_depIdxs,
		MessageInfos:      file_internal_api_localctrlapi_local_controller_api_proto_msgTypes,
	}.Build()
	File_internal_api_localctrlapi_local_controller_api_proto = out.File
	file_internal_api_localctrlapi_local_controller_api_proto_rawDesc = nil
	file_internal_api_localctrlapi_local_controller_api_proto_goTypes = nil
	file_internal_api_localctrlapi_local_controller_api_proto_depIdxs = nil
}
